# Generated by Django 4.2 on 2026-06-02 17:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmail_message_id', models.CharField(blank=True, max_length=255)),
                ('sender', models.EmailField(max_length=254)),
                ('recipient', models.EmailField(max_length=254)),
                ('cc', models.CharField(blank=True, max_length=500)),
                ('bcc', models.CharField(blank=True, max_length=500)),
                ('subject', models.CharField(max_length=500)),
                ('body', models.TextField()),
                ('html_body', models.TextField(blank=True)),
                ('is_read', models.BooleanField(default=False)),
                ('is_sent', models.BooleanField(default=False)),
                ('is_draft', models.BooleanField(default=True)),
                ('is_starred', models.BooleanField(default=False)),
                ('thread_id', models.CharField(blank=True, max_length=255)),
                ('in_reply_to', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AILog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('compose', 'Compose Email'), ('improve', 'Improve Email'), ('reply', 'Generate Reply'), ('subject', 'Generate Subject'), ('summarize', 'Summarize Email')], max_length=20)),
                ('tone', models.CharField(choices=[('formal', 'Formal'), ('friendly', 'Friendly'), ('concise', 'Concise'), ('assertive', 'Assertive'), ('professional', 'Professional')], default='professional', max_length=20)),
                ('input_text', models.TextField()),
                ('output_text', models.TextField()),
                ('tokens_used', models.IntegerField(default=0)),
                ('processing_time', models.FloatField(default=0.0)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='email',
            index=models.Index(fields=['user', '-created_at'], name='emails_emai_user_id_4caaad_idx'),
        ),
        migrations.AddIndex(
            model_name='email',
            index=models.Index(fields=['is_sent'], name='emails_emai_is_sent_26c293_idx'),
        ),
        migrations.AddIndex(
            model_name='email',
            index=models.Index(fields=['is_read'], name='emails_emai_is_read_3957a2_idx'),
        ),
        migrations.AddIndex(
            model_name='ailog',
            index=models.Index(fields=['user', '-created_at'], name='emails_ailo_user_id_57ce58_idx'),
        ),
        migrations.AddIndex(
            model_name='ailog',
            index=models.Index(fields=['action'], name='emails_ailo_action_d0cb0a_idx'),
        ),
    ]
