# Generated by Django 4.2 on 2026-06-04 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='ailog',
            name='emails_ailo_user_id_57ce58_idx',
        ),
        migrations.RemoveIndex(
            model_name='ailog',
            name='emails_ailo_action_d0cb0a_idx',
        ),
        migrations.AddField(
            model_name='email',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='email',
            name='gmail_message_id',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='email',
            index=models.Index(fields=['gmail_message_id'], name='emails_emai_gmail_m_4f0599_idx'),
        ),
    ]
